# ---------------------------------------------------------------------------
# INFRASTRUCTURE ONLY (Hetzner Cloud).
#
# Creates the SSH key, private network, a default-deny firewall (only 22 + 443),
# and one server whose ONLY unattended-boot work is a cloud-init payload. It
# configures NO services. The single handover to Ansible is a generated
# inventory written from state (bottom of this file).
#
# No remote-exec / provisioners: configuration is Ansible's job.
# ---------------------------------------------------------------------------

locals {
  name = {
    ssh_key  = "${var.project_prefix}-key"
    network  = "${var.project_prefix}-net"
    subnet   = "${var.project_prefix}-subnet"
    firewall = "${var.project_prefix}-fw"
    server   = "${var.project_prefix}-server"
  }

  # Hetzner network zone for the chosen location. German zones map to eu-central.
  location_to_zone = {
    nbg1 = "eu-central"
    fsn1 = "eu-central"
    hel1 = "eu-central"
    ash  = "us-east"
    hil  = "us-west"
    sin  = "ap-southeast"
  }
  network_zone = lookup(local.location_to_zone, var.location, "eu-central")

  common_labels = {
    project = var.project_prefix
    managed = "terraform"
  }
}

# SSH key uploaded to the project (nothing pre-exists in the project).
resource "hcloud_ssh_key" "admin" {
  name       = local.name.ssh_key
  public_key = file(pathexpand(var.ssh_public_key_path))
  labels     = local.common_labels
}

# Private network + subnet.
resource "hcloud_network" "internal" {
  name     = local.name.network
  ip_range = var.network_ip_range
  labels   = local.common_labels
}

resource "hcloud_network_subnet" "internal" {
  network_id   = hcloud_network.internal.id
  type         = "cloud"
  network_zone = local.network_zone
  ip_range     = var.subnet_ip_range
}

# Default-deny firewall: only SSH (22) and HTTPS (443) inbound. Outbound is left
# unrestricted so the server can reach the Elastic APT repo. Elasticsearch:9200
# and Kibana:5601 are never in this list, so they are unreachable from outside.
resource "hcloud_firewall" "edge" {
  name   = local.name.firewall
  labels = local.common_labels

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "22"
    source_ips  = var.allowed_ssh_cidrs
    description = "SSH (admin access)"
  }

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "443"
    source_ips  = var.allowed_https_cidrs
    description = "HTTPS (the only application port)"
  }

  # ICMP echo so the host is pingable for basic reachability checks.
  rule {
    direction   = "in"
    protocol    = "icmp"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "ping"
  }
}

# The server. Its only unattended work is the cloud-init payload; everything
# else is Ansible. delete_protection MUST be false so teardown always works.
resource "hcloud_server" "elk" {
  name         = local.name.server
  server_type  = var.server_type
  image        = var.server_image
  location     = var.location
  ssh_keys     = [hcloud_ssh_key.admin.id]
  firewall_ids = [hcloud_firewall.edge.id]
  labels       = local.common_labels

  delete_protection  = false
  rebuild_protection = false

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }

  network {
    network_id = hcloud_network.internal.id
  }

  # cloud-init: create the admin user, disable root/password SSH, set
  # vm.max_map_count, install python3, and drop a completion marker Ansible waits on.
  user_data = templatefile("${path.module}/templates/cloud-init.yaml.tftpl", {
    admin_user     = var.admin_user
    ssh_public_key = trimspace(file(pathexpand(var.ssh_public_key_path)))
  })

  # The subnet must exist before the server attaches to the network.
  depends_on = [hcloud_network_subnet.internal]
}

# ---------------------------------------------------------------------------
# THE HANDOVER: render the Ansible inventory from state. No human copies the IP.
# ---------------------------------------------------------------------------
resource "local_file" "ansible_inventory" {
  filename        = var.generated_inventory_path
  file_permission = "0644"

  content = <<-YAML
    ---
    # GENERATED BY TERRAFORM - DO NOT EDIT. Regenerate with `terraform apply`.
    all:
      vars:
        ansible_user: "${var.admin_user}"
        ansible_ssh_private_key_file: "${pathexpand(var.ssh_private_key_path)}"
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=${abspath("${path.module}/../ansible/.ssh_known_hosts")}"
        elastic_stack_version: "${var.elastic_stack_version}"
        public_ipv4: "${hcloud_server.elk.ipv4_address}"
        published_https_port: 443
      children:
        elk:
          hosts:
            elk_server:
              ansible_host: "${hcloud_server.elk.ipv4_address}"
  YAML
}
